version: 0.2
phases:
 install:
   commands:
     - echo
 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps

 post_build:
   commands:
     - echo Build completed on `date`
     - ls
